name: Build site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: "${GITHUB_WORKSPACE}/source/"
          ref: 'main'

      - name: Checkout gh-pages branch for output
        uses: actions/checkout@v2
        with:
          path: "${GITHUB_WORKSPACE}/dest/""
          ref: 'gh-pages'

      - name: Go in source dir
        run: cd "${GITHUB_WORKSPACE}/source/""

      - name: Install JS librairies
        run: npm install

      - name: Remove useless files
        run: rm -r .gitignore package.json package-lock.json .github

      - name: Add .nojekyll
        run: touch .nojekyll

      - name: Copy files to dest dir
        run: cp -a * "${GITHUB_WORKSPACE}/dest/"

      - name: Push site into gh-pages branch
        uses: EndBug/add-and-commit@v8.0.2
        with:
          remove: .gitignore package.json package-lock.json .github
          push: true
          cwd: "${GITHUB_WORKSPACE}/dest"
