name: Build site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source
          ref: 'main'

      - name: Checkout gh-pages branch for output
        uses: actions/checkout@v2
        with:
          path: dest
          ref: 'gh-pages'

      - name: Install JS librairies
        run: npm install
        working-directory: source

      - name: Remove useless files
        run: rm -r .gitignore package.json package-lock.json .github
        working-directory: source

      - name: Add .nojekyll
        run: touch .nojekyll
        working-directory: source

      - name: Copy files to dest dir
        run: cp -a source/* dest/

      - name: Remove all commits from gh-pages branch
        run: git -c sequence.editor="sed -i '1s/^/d\n/'" rebase --interactive HEAD
        working-directory: dest

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dest
