name: Build site

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          rm -r .gitignore package.json package-lock.json .github
          touch .nojekyll
      - uses: EndBug/add-and-commit@v8.0.2
        with:
          new_branch: gh-pages
          push: true
