name: Build site

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JS librairies
        run: npm install
      - name: Add .nojekyll
        run: touch .nojekyll
      - name: Push site into gh-pages branch
        uses: EndBug/add-and-commit@v8.0.2
        with:
          remove: .gitignore package.json package-lock.json .github
          new_branch: gh-pages
          push: true
